title: "Simulation of a pivoting elastic beam";

/* Gravity vector */
gravity[1]: -9.81;
gravity[2]: 0;
gravity[3]: 0;

mass[1]: 1;
Ixx[1]: 1;
Iyy[1]: 0.1;
Izz[1]: 1;
T0G[1]:  Trotx(q[1]);


mass[2]: 1;
Ixx[2]: 0.1;
Iyy[2]: 0.1;
Izz[2]: 0.1;

BodyRef[2]: 1;
TrefG[2]:  Tdisp(0, q[2], q[3]);


/* Initial conditions */
qdi[1]: 1;
qdi[3]: 1;


/* Simulation parameters */
FinalTime: 2;
StepSave: 0.05;
StepMax: 0.01;

appliedForces():= (
    appliedF[2]: matrix([0], [-4*q[2] - 0.01*qd[2]], [-4*q[3] - 0.01*qd[3]])          
);

