title: "Simulation of a pivoting elastic beam";

/* Gravity vector */
gravity[1]: -9.81;
gravity[2]: 0;
gravity[3]: 0;

mass[1]: 1;
Ixx[1]: 1;
Iyy[1]: 0.1;
Izz[1]: 1;
T0G[1]:  Troty(q[2]).Trotx(q[1]);

elastic_dof[2]: [q[3]];
PHI: [makelist([0, (0.2*i)^2, 0], i, 1, 6)];
rr: makelist([1*i, 0, 0], i, 1, 6);
mm: makelist(0.1, i, 1, 6);
ebody[2]: calcElasticModeLumpedPrecomputed(PHI, rr, mm);
ebody[2]@K@M0[1, 1]: 1;
ebody[2]@D@M0[1, 1]: 0.01;
ebody[2]@I@M0[1, 1]: 1e-5;

BodyRef[2]: 1;
TrefG[2]:  Trotx(0);


/* Initial conditions */
qdi[1]: 1;
qdi[3]: 1;


/* Simulation parameters */
FinalTime: 2;
StepSave: 0.05;
StepMax: 0.01;
