title: "Simulation of a pivoting elastic beam";

/* Gravity vector */
gravity[1]: -9.81;
gravity[2]: 0;
gravity[3]: 0;

mass[1]: 1;
Ixx[1]: 1;
Iyy[1]: 0.1;
Izz[1]: 1;
T0G[1]:  Trotx(q[1]);

elastic_dof[2]: [q[2]];
PHI: [makelist([-float(1/sqrt(2))*(0.2*i)^2, float(1/sqrt(2))*(0.2*i)^2, 0], i, 1, 6)];
rr: makelist([float(1/sqrt(2))*i, float(1/sqrt(2))*i, 0], i, 1, 6);
mm: makelist(0.1, i, 1, 6);
ebody[2]: calcElasticModeLumpedPrecomputed(PHI, rr, mm);
ebody[2]@K@M0[1, 1]: 1;
ebody[2]@D@M0[1, 1]: 0.1;

BodyRef[2]: 1;
TrefG[2]:  Trotz(-%pi/4);


/* Initial conditions */
qdi[1]: 1;
qdi[3]: 1;


/* Simulation parameters */
FinalTime: 20;
StepSave: 0.05;
StepMax: 0.01;
