title: "Simulation of a pivoting elastic beam";

/* Gravity vector */
gravity[1]: -9.81;
gravity[2]: 0;
gravity[3]: 0;

mass[1]: 1;
Ixx[1]: 1;
Iyy[1]: 0.1;
Izz[1]: 1;
T0G[1]:  Troty(q[2]).Trotx(q[1]);

elastic_dof[2]: [q[3]];
PHI: [makelist([0, (0.2*i)^2, 0], i, 1, 6)];
rr: makelist([1*i, 0, 0], i, 1, 6);
mm: makelist(0.1, i, 1, 6);
ebody[2]: calcElasticModeLumpedPrecomputed(PHI, rr, mm);
ebody[2]@K: [1];
ebody[2]@D: [0.01];
mass[2]: ebody[2]@m;
Ixx[2]: 0.00001; /*ebody[2]@I[1, 1];*/
Iyy[2]: ebody[2]@I[2, 2];
Izz[2]: ebody[2]@I[3, 3];
Ixy[2]: ebody[2]@I[1, 2];
Ixz[2]: ebody[2]@I[1, 3];
Iyz[2]: ebody[2]@I[2, 3];
BodyRef[2]: 1;
TrefG[2]:  Trotx(0);


/* Initial conditions */
qdi[1]: 1;
qdi[3]: 1;


/* Simulation parameters */
FinalTime: 2;
StepSave: 0.05;
StepMax: 0.01;
